# Display an ascii robot
print("##########")
print("#        #")
print("#        #")
print("##########")
print("    ##    ")
print("    ##    ")
print("    ##    ")
print("##########")
print("##########")
print("##########")
print("##########")
print("  ##  ##  ")
print("  ##  ##  ")
print("  ##  ##  ")
print("  ##  ##  ")

# Ask user to enter a character for the eye
print("Please enter a character for the eye")
character = input()
print("Beep's expression is now as follows:)")
print("##########")
print("#  o  o  #")
print("#  ----  #")
print("##########")
print("    ##    ")
print("    ##    ")
print("    ##    ")
print("##########")
print("##########")
print("##########")
print("##########")
print("  ##  ##  ")
print("  ##  ##  ")
print("  ##  ##  ")
print("  ##  ##  ")